import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const firaCode = Fira_Code({
    variable: "--font-fira-code",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "MTG Deck Builder",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${firaCode.variable} antialiased flex flex-col h-[100vh] justify-between align-middle`}
            >
                <Navbar />

                {children}

                <Footer />
            </body>
        </html>
    );
}
